// JavaScript to open and close the burger menu
function openMenu() {
    document.getElementById('burgerMenu').style.display = 'block';
}

function closeMenu() {
    document.getElementById('burgerMenu').style.display = 'none';
}

// Add event listener to close the menu when clicking outside of it
document.addEventListener('click', function(event) {
    const menu = document.getElementById('burgerMenu');
    const burgerIcon = document.querySelector('.burger-menu');

    if (!menu.contains(event.target) && event.target !== burgerIcon) {
        closeMenu();
    }
});


const positions = ["69", "Missionary", "Doggy Style", "Cowgirl", "Ekiben", "Spooning"];
const locations = ["Garden", "Kitchen", "Living Room", "Bedroom", "Bathroom", "Library"];

const stories = {
"69_Garden": "Under the moonlit sky, amidst the gentle rustle of leaves, they explored each other with fervor, their bodies entwined in nature's embrace. The cool night air heightened their senses, each gust of wind a whispered promise of what was to come. Their hands roamed freely over each other’s bodies, discovering new terrains, while the scent of fresh grass and blooming flowers surrounded them. The soft earth beneath provided a steady foundation as they moved in a slow, deliberate dance, savoring the feeling of skin against skin. Every touch was a silent conversation, every sigh a shared secret, and as the stars above watched, they knew this moment was etched in the very fabric of the universe. Their shared breaths formed a rhythm with the nocturnal symphony around them, blending their love with the essence of the night.",

    "69_Kitchen": "An adventurous night, where every surface in the kitchen became an invitation to explore the forbidden thrill of passion. The cool countertop was a thrilling contrast to their heated desire, every movement a bold declaration of their passion. They navigated the space with a playful urgency, finding pleasure in every unexpected corner. As their bodies intertwined, they knocked over a bowl of fruit, the rolling apples echoing their playful, passionate energy. Every kiss tasted sweeter, every touch was an adventure in sensation, their love a dance of hunger and satisfaction. The kitchen, once a place of everyday routines, transformed into a landscape of erotic exploration, each surface a new chapter in their story. They moved with a fluid grace, turning the mundane into the extraordinary, each moment a delicious blend of heat and sweetness.",

    "69_Living Room": "On the soft rug, bathed in the glow of a crackling fireplace, they found a playground of passion. The flickering flames cast dancing shadows across their entwined bodies, highlighting every curve and muscle in a moving tableau of desire. Each shift and movement was a careful exploration, every caress a silent testament to their shared longing. The plush fabric beneath them cushioned their playful tussle, while the warmth of the fire contrasted with the coolness of the air, adding to the thrill of their intimate dance. Their breaths mingled in the quiet room, each sigh a shared song, their bodies moving in perfect harmony to the quiet rhythm of the night. As they explored each other, they found a deeper connection, a bond that went beyond the physical, becoming a sacred communion of souls.",

    "69_Bedroom": "In the intimacy of their bedroom, the world outside ceased to exist, leaving only the two of them in a cocoon of warmth and love. They entwined in a dance of pleasure, savoring every moment of closeness and connection. The soft sheets were cool against their skin, creating a sensual contrast with the heat that flowed between them. Every movement was deliberate, every touch a tender promise, their bodies moving as one in a rhythm that spoke of deep trust and boundless affection. The bed creaked softly in time with their movements, their whispers filling the room with a language only they understood. As they moved together in perfect harmony, they felt a deep connection that went beyond the physical, a bond forged in trust and mutual respect. In this sacred space, they were free to explore their love in all its beautiful, infinite forms.",

    "69_Bathroom": "The steamy bathroom turned into a sanctuary of sensation, where warm water cascaded over their bodies, mingling with the sweat of their shared desire. The droplets glistened like jewels on their skin, every touch electrifying under the soothing spray. The tiled walls echoed with soft gasps and whispered names, a melody of love that filled the humid air. Each movement under the water was a testament to their unspoken bond, their bodies finding a rhythm that was both natural and profound. As they held each other close, their mouths exploring every inch of their lover’s skin, they found solace in the simple, pure joy of being together, the steam rising around them like a protective veil. The heat of the water was a stark contrast to the cool tiles, a dichotomy that heightened their senses and amplified their pleasure.",

    "69_Library": "Amongst the bookshelves, they engaged in an intellectual and physical exploration, every touch and taste revealing new chapters of pleasure. The scent of old paper and leather filled their senses, mingling with the heady aroma of their desire. As they moved, the quiet rustle of turning pages became a subtle symphony of sound, blending with their shared breaths and soft sighs. Every stroke was a revelation, every kiss a new discovery, their bodies writing a narrative of passion that was as timeless as the stories surrounding them. In this sacred space of knowledge, they became authors of their own tale, a story told through touch, taste, and whispered words of love. Their love was a living, breathing story that unfolded in the quiet sanctuary of the library, each moment a line in the narrative of their desire, blending intellect with pure, unbridled passion.",
    
    "Missionary_Garden": "Amidst the blooming flowers, they embraced in the most intimate way, grounding themselves in the earth as they soared to new heights of connection. The garden around them was alive with color and scent, every flower a silent witness to their love. The soft petals brushed against their skin, a gentle caress from nature itself, as they moved together in a rhythm that was as old as time. Each breath they took was filled with the scent of blossoms and fresh grass, a reminder of the world they were so deeply connected to. Their hands roamed freely, discovering new places to touch and be touched, their bodies melting into one another, becoming a part of the natural beauty around them. As they held each other close, they felt the pulse of life all around them, their love a living, breathing thing that flourished in the open air, grounded in the earth and reaching for the stars.",

    "Missionary_Kitchen": "In the kitchen, love became the main ingredient, each thrust and caress blending into a perfect recipe of passion. The cool tiles beneath them provided a stark contrast to the heat of their bodies, grounding them as they moved together in a slow, deliberate rhythm. The scent of spices lingered in the air, a subtle reminder of the meal they had abandoned in favor of this deeper, more primal hunger. Their hands roamed freely, discovering new places to touch and be touched, their bodies melting into one another. The kitchen, once a place of everyday routines, became a sanctuary of intimacy, where every surface was a new discovery, every moment a delicious blend of flavors. They moved with a natural grace, their love a feast for the senses, each taste more intoxicating than the last.",

    "Missionary_Living Room": "On the couch, they found both comfort and excitement, their bodies moving together in a timeless rhythm of love. The soft cushions beneath them were a perfect complement to the firmness of their embrace, each touch a silent conversation of trust and desire. The dim light of a single lamp cast gentle shadows across their skin, highlighting every curve and contour as they moved. As their breaths mingled in the quiet of the room, they found a deeper connection, a bond that went beyond the physical, becoming a sacred communion of souls. Every whispered word, every gentle caress was a testament to their love, a love that was both fierce and gentle, timeless and ever-renewing. As they held each other close, they felt a deep sense of peace, their love a quiet sanctuary in the middle of a busy world.",

    "Missionary_Bedroom": "The classic embrace of lovers in the comfort and warmth of their sanctuary, where every whisper and touch deepened their bond. The soft glow of moonlight through the curtains bathed them in a silver light, creating a serene backdrop for their tender exploration. Each movement was deliberate, every touch a pledge of love, their bodies moving together with a natural grace that spoke of deep understanding and mutual respect. As they lay intertwined, their breaths coming in soft, steady waves, they found solace in the closeness, their love a warm cocoon that shielded them from the world outside. In the quiet of their bedroom, they rediscovered each other anew, their connection deepening with every beat of their hearts, their love a constant, unwavering presence in their lives.",

    "Missionary_Bathroom": "In the steamy bathroom, they pressed against the cool tiles, their bodies igniting with a fiery, passionate energy. The mist clung to their skin, adding a layer of sensuality to their every touch. The water flowed down their bodies, creating a symphony of soft sounds that echoed against the walls. With every kiss, every caress, they delved deeper into each other, finding a connection that was both physical and spiritual. The warmth of the water was a stark contrast to the coolness of the tiles, a dichotomy that heightened their senses and amplified their pleasure. In this intimate space, they found a world that was theirs alone, a world filled with love and passion, where every movement was a dance, every touch a promise of forever.",

    "Missionary_Library": "Surrounded by the wisdom of the ages, they created their own story, their bodies coming together in a symphony of love and desire. The soft rustle of pages filled the air, a gentle reminder of the countless stories that had come before them. As they moved together, they wrote their own chapter, one filled with passion, tenderness, and a deep, abiding love. Every touch was a word, every kiss a sentence, their bodies crafting a narrative that was both ancient and new. In the quiet sanctuary of the library, they found a space where they could be completely themselves, their love a timeless tale that would be remembered long after the last page was turned. The shelves around them seemed to lean in, listening to their whispered confessions of love, their silent promises to one another, their love story unfolding in the quiet between the words.",
    
    "Doggy Style_Garden": "Hidden amongst the tall grass, their bodies moved in a primal rhythm, the scent of earth and flowers heightening their senses. The natural world around them seemed to come alive with their movements, each sway of their hips echoing in the rustling leaves. The cool breeze whispered secrets to their skin, adding to the tantalizing mix of sensations. Every thrust was a deeper dive into the untamed wilderness of their desire, their bodies moving with a fierce, unbridled energy that spoke of freedom and raw passion. The ground beneath them was soft, cushioning their knees, while the tall grass swayed with their rhythm, hiding them away in a world of their own. The scent of fresh earth and blooming flowers mingled with the intoxicating aroma of their love, creating an ambiance that was as wild and beautiful as the love they shared. In the midst of nature’s embrace, they surrendered to their most basic instincts, finding a primal joy in the simplicity of their connection.",

    "Doggy Style_Kitchen": "Against the kitchen counter, they embraced the raw, untamed nature of their passion, every movement igniting a new flame of desire. The cool countertop pressed against heated skin, creating a stark contrast that heightened every sensation. Their hands gripped the edge of the counter, knuckles white with the intensity of their hold, finding stability in the midst of their shared storm. Pots and pans clattered in response to their movements, adding a soundtrack of spontaneity to their dance of desire. Each thrust was a bold statement of their love, a declaration of their need for each other, their bodies moving in perfect harmony to a rhythm as old as time. The kitchen, a place of nourishment and creation, became a stage for their most primal expressions, every surface an opportunity for a new kind of exploration. The smell of spices and simmering flavors mingled with the heat of their passion, turning the kitchen into a playground where every ingredient added to the recipe of their love.",

    "Doggy Style_Living Room": "On the plush carpet, they surrendered to their instincts, each thrust echoing with the rhythm of their beating hearts. The thick pile of the carpet cushioned their knees, offering a soft base for their movements. The room was filled with the soft glow of candlelight, casting shadows that danced along with them, creating an intimate setting that felt both sacred and exhilarating. Their bodies moved together in a symphony of passion, every movement a silent song of desire. The warmth of the room, the softness beneath them, and the coolness of the air created a perfect balance of sensations, each one enhancing the other. As they moved together, they found a deeper connection, a bond that was both fierce and tender, primal and gentle. Their breaths came in soft gasps, mingling in the air above them, forming a quiet chorus that spoke of their shared longing and the deep love that fueled their every move.",

    "Doggy Style_Bedroom": "In their private retreat, they explored a more primal side, their bodies finding perfect synchronization in their desires. The bedroom, their sanctuary, was filled with a comforting warmth that invited exploration and intimacy. The soft sheets beneath them were cool against their heated skin, a stark contrast that only heightened their desire. Every movement was deliberate, every touch a tender command, their bodies moving in a rhythm that spoke of deep understanding and mutual respect. The bed creaked softly in time with their movements, their whispers filling the room with a language only they understood. As they moved together, they explored new depths of their connection, finding a primal joy in the simplicity of their love. The room was filled with the soft sounds of their shared pleasure, a quiet symphony of passion that resonated with the deep love that bound them together. In this sacred space, they were free to be completely themselves, their love a wild, untamed force that knew no bounds.",

    "Doggy Style_Bathroom": "With hands gripping the sink, they let go of all restraint, their passion mirrored in the fogged-up mirrors around them. The cool porcelain of the sink pressed against their skin, a stark contrast to the heat of their bodies. The bathroom was filled with steam, the warm mist clinging to their skin, amplifying every touch, every kiss, every whispered word. The water ran in a steady stream, its soft murmur adding a soothing backdrop to their intense, passionate dance. Each movement was a release, a surrender to the raw, unfiltered desire that coursed through their veins. The mirrors around them reflected their intertwined forms, capturing the beauty of their connection in a hundred different angles. Every thrust was a deeper plunge into their shared desire, every gasp a testament to the intensity of their love. The bathroom, once a place of routine, became a sanctuary of sensation, where every movement was a dance, every touch a promise of deeper intimacy.",

    "Doggy Style_Library": "Bent over the desk, they lost themselves in a heated exploration, their breath heavy with both lust and literary inspiration. The scent of old books and leather filled their senses, mingling with the heady aroma of their desire. The wooden desk creaked softly under their weight, its surface a cool contrast to the heat of their bodies. The quiet rustle of turning pages became a subtle symphony of sound, blending with their shared breaths and soft gasps. Every stroke was a revelation, every kiss a discovery, their bodies writing a narrative of passion that was as timeless as the stories surrounding them. As they moved together, they created a new story, one filled with passion, tenderness, and a deep, abiding love. The library, a place of knowledge and quiet contemplation, became a stage for their most primal expressions, every book a silent witness to their love. In this sacred space of wisdom, they found a new kind of learning, one that was both intellectual and deeply, passionately physical.",
    
    "Cowgirl_Garden": "In the garden's embrace, she rode him with the confidence of a goddess, the world around them becoming a blur of pleasure. The soft grass beneath them provided a gentle cushion, each blade a delicate caress against their skin. The scent of blooming flowers mingled with the intoxicating aroma of their shared desire, creating a heady blend that filled their senses. As she moved with a steady, confident rhythm, her body became one with the natural world around them, each movement a celebration of life and love. The garden, bathed in the soft glow of the moonlight, seemed to pulse with their energy, the leaves whispering secrets to the wind. Her every motion was a command, a declaration of her power and control, and he responded with equal fervor, his hands gripping her hips, guiding her as they ascended to new heights of ecstasy. In this sacred space of nature, they found a freedom that was both exhilarating and grounding, their love a wild, untamed force that knew no boundaries.",

    "Cowgirl_Kitchen": "On the sturdy kitchen table, she took control, her movements bold and rhythmic, creating a masterpiece of pleasure. The cool surface of the table pressed against their heated skin, a stark contrast that only heightened their sensations. Her hands gripped the edges of the table, finding stability as she moved with a confident grace, her body a symphony of motion. The kitchen, once a place of nourishment and routine, became a stage for their most primal expressions, every thrust a bold statement of her dominance. She rode him with a fierce determination, her eyes locked onto his, communicating a desire that was both intense and undeniable. The clatter of utensils in the drawers below added a spontaneous, almost musical accompaniment to their dance of passion. With every rise and fall, she drew them deeper into their shared world, a place where nothing existed but their love and the relentless rhythm of their bodies.",

    "Cowgirl_Living Room": "On the armchair, she took the lead, their bodies moving in perfect harmony, a dance of dominance and surrender. The plush fabric of the chair cushioned their movements, offering a soft contrast to the firm intensity of their connection. She moved with a deliberate, controlled grace, her body dictating the rhythm of their shared experience. The living room, bathed in the warm glow of a single lamp, became a sanctuary of intimacy, where every shadow on the walls told a story of their love. He surrendered to her completely, his hands resting on her thighs, guiding her movements but allowing her to set the pace. With each rise and fall, they found a new depth of connection, a bond that went beyond the physical, becoming a sacred communion of souls. Her every motion was a testament to her strength and confidence, his every response a tribute to his trust and devotion. Together, they created a dance that was both fierce and tender, a perfect blend of power and passion.",

    "Cowgirl_Bedroom": "Straddling him on the bed, she commanded their love with every motion, every rise and fall a testament to their desire. The soft sheets beneath them were cool against their skin, a stark contrast to the heat that radiated from their bodies. She moved with a slow, deliberate grace, her eyes never leaving his, her every movement a silent command that he was all too eager to obey. The bed, their sanctuary, creaked softly in time with their rhythm, a gentle reminder of the love they had built together over the years. Her hands rested on his chest, feeling the steady beat of his heart beneath her palms, each thump a testament to his desire for her. As she moved, she felt a surge of power and confidence, knowing that in this moment, she was the goddess of their love, the one who held all the power. He responded to her every command with equal fervor, his hands gripping her hips, guiding her movements as they ascended to new heights of ecstasy.",

    "Cowgirl_Bathroom": "On the edge of the bathtub, she claimed him with fierce determination, her every move sending ripples of pleasure through them both. The cool porcelain of the tub pressed against their skin, grounding them in the intensity of their connection. The warm water cascaded down around them, adding a soothing backdrop to their passionate dance. She moved with a confident, deliberate grace, her body dictating the rhythm of their shared experience. The bathroom, once a place of routine, became a sanctuary of sensation, where every touch was a promise, every kiss a declaration of their love. Her hands gripped his shoulders, her nails digging into his skin as she rode him with a fierce intensity, her every movement a testament to her strength and confidence. He responded to her with equal passion, his hands exploring every curve of her body, finding new places to touch and be touched. Together, they created a moment of pure connection and love, a quiet dance of intimacy that would be cherished for all time.",

    "Cowgirl_Library": "In the quiet of the library, she took the reins, their whispered moans mingling with the silence of the forgotten pages around them. The scent of old books and leather filled their senses, creating an atmosphere that was both scholarly and sensual. The soft, plush carpet cushioned their movements, offering a gentle contrast to the intensity of their connection. She moved with a deliberate, controlled grace, her body dictating the rhythm of their shared experience. The library, a place of quiet contemplation, became a stage for their most primal expressions, every movement a bold statement of her dominance. As she rode him, her eyes locked onto his, communicating a desire that was both intense and undeniable. The quiet rustle of pages turning added a subtle soundtrack to their dance of passion, each thrust echoing with the rhythm of their beating hearts. Together, they created a story that was both intellectual and deeply, passionately physical, a tale that would be remembered long after the last page was turned.",

    "Ekiben_Garden": "With her back to him, she faced the open sky, riding him with a free spirit, the wild energy of nature coursing through their veins. The soft grass beneath their feet cushioned their movements, while the breeze carried the scent of wildflowers and fresh earth, adding a heady aroma to their passion. The open sky above seemed endless, a canvas of stars twinkling down as silent witnesses to their love. She moved with a rhythm that was both wild and controlled, each movement a celebration of freedom and unbridled desire. His hands gripped her hips, steadying her as she moved, guiding her with gentle strength. With every rise and fall, she felt the power of the earth beneath her and the vastness of the sky above, their love a bridge between the two. They were a part of nature itself, their bodies moving in perfect harmony with the natural world around them. As they lost themselves in each other, they found a deeper connection, a bond that was as wild and untamed as the garden around them.",

    "Ekiben_Kitchen": "On the kitchen floor, she took him from a new angle, every movement a bold statement of their insatiable desire. The cool tiles beneath them were a stark contrast to the heat of their bodies, grounding them in the intensity of their connection. She moved with a deliberate, powerful grace, her every motion a clear declaration of her confidence and control. The kitchen, a place of creation and nourishment, became a playground of passion, each surface a new possibility, every angle an opportunity for exploration. As she leaned forward, her hands bracing against the floor, she felt his hands gripping her waist, pulling her closer with each thrust. The room was filled with the sounds of their shared pleasure, a quiet symphony of soft gasps and whispered words that echoed against the walls. Together, they created a dance that was both fierce and tender, their bodies moving in perfect synchrony, each movement a testament to their insatiable desire and deep, abiding love.",

    "Ekiben_Living Room": "On the chaise lounge, she moved with confidence and grace, every shift in position revealing a new depth of pleasure. The plush fabric of the chaise lounge provided a soft, inviting surface, cushioning their movements and adding a layer of comfort to their passionate dance. She straddled him with a commanding presence, her body moving with a fluid, almost hypnotic rhythm. Each change in position was a deliberate exploration, a search for new angles, new sensations. The living room, bathed in the warm glow of a crackling fireplace, became a sanctuary of intimacy, where every shadow told a story of their love. His hands roamed her body, exploring every curve, every contour, guiding her with a gentle strength. As they moved together, they found a new level of connection, a bond that went beyond the physical, becoming a sacred communion of souls. Their love was a dance, a perfect blend of power and passion, a beautiful expression of their desire for each other.",

    "Ekiben_Bedroom": "In the dim light of their bedroom, she rode him backwards, savoring the power and control with every thrust. The soft glow of the bedside lamp cast long shadows on the walls, creating an intimate, almost ethereal atmosphere. She moved with a slow, deliberate grace, her every motion a clear expression of her confidence and control. The bed, their sanctuary, creaked softly under their weight, its soft sheets cool against their heated skin. With each thrust, she felt a surge of power, a rush of adrenaline that coursed through her veins. He responded with equal fervor, his hands gripping her thighs, guiding her movements with a steady strength. Together, they created a moment of pure connection, a quiet dance of intimacy that was both fierce and tender, wild and controlled. Their love was a powerful force, a beautiful expression of their deep, unbreakable bond, a bond that was strengthened with every movement, every touch, every whispered word.",

    "Ekiben_Bathroom": "Against the bathroom sink, she looked over her shoulder with a playful smile, leading their passion with commanding energy. The cool porcelain of the sink pressed against her body, a stark contrast to the heat of their connection. The mirror in front of them reflected their entwined forms, capturing the beauty of their love in a hundred different angles. She moved with a slow, deliberate rhythm, her body dictating the pace of their shared experience. The bathroom, filled with the scent of fresh soap and steam, became a stage for their most primal expressions, every movement a bold statement of her dominance. His hands gripped her hips, steadying her as she moved, guiding her with a gentle strength. Together, they created a dance that was both fierce and tender, a beautiful blend of power and passion, a quiet symphony of love that filled the room. The fogged-up mirrors mirrored their passion, capturing the intensity of their connection in a haze of steam and desire.",

    "Ekiben_Library": "On a sturdy library table, she rode him with a seductive sway, their bodies writing a story of wild, unrestrained passion. The scent of old books and leather filled their senses, mingling with the heady aroma of their desire. The table creaked softly under their weight, its surface a cool contrast to the heat of their bodies. She moved with a deliberate, controlled grace, her every motion a clear declaration of her confidence and control. The library, a place of quiet contemplation, became a stage for their most primal expressions, every movement a bold statement of their desire. As they moved together, they created a new story, one filled with passion, tenderness, and a deep, abiding love. The quiet rustle of pages turning added a subtle soundtrack to their dance of passion, each thrust echoing with the rhythm of their beating hearts. Together, they wrote a narrative that was both intellectual and deeply, passionately physical, a tale that would be remembered long after the last page was turned.",
    
    "Spooning_Garden": "Lying close in the tall grass, they found a tender connection, the cool breeze of the garden surrounding their soft, rhythmic movements. The grass swayed gently around them, the soft rustling of leaves creating a soothing melody that harmonized with their steady breathing. The scent of fresh earth and blooming flowers filled the air, enhancing the natural intimacy of their embrace. They lay close together, her back nestled against his chest, their bodies fitting together as if they were two halves of the same whole. His arm draped over her waist, holding her close, each gentle movement a wordless expression of love. The cool breeze brushed against their skin, a gentle contrast to the warmth radiating between them. As they moved in slow, rhythmic unison, they found solace in each other's presence, their love a quiet, steady force that grew stronger with every passing moment. In the garden's embrace, they felt a deep, abiding connection to each other and the natural world around them.",

    "Spooning_Kitchen": "On the kitchen floor, they spooned with a deep, intimate rhythm, each gentle thrust and soft whisper melting into the warmth of their embrace. The cool tiles beneath them offered a firm foundation, grounding them as they moved together in a slow, deliberate dance of love. The kitchen, usually a place of bustling activity, was transformed into a quiet haven of intimacy, where every touch, every sigh was a tender confession of their love. She lay nestled against him, her body curving perfectly into his, their hearts beating in synchrony. His hand gently traced the contours of her body, finding solace in the softness of her skin. Each movement was a delicate exploration, a journey into the depths of their connection. As they whispered sweet nothings into each other's ears, they found themselves lost in a world of their own making, where love was the only reality that mattered. The warmth of their embrace was like a cozy fire, melting away all worries, leaving only the pure, unadulterated joy of being together.",

    "Spooning_Living Room": "Curled up on the sofa, they spooned with gentle passion, their bodies fitting together like perfect puzzle pieces in the warmth of their home. The soft cushions cradled them, offering a comforting embrace that made them feel safe and secure. The glow of a nearby lamp cast a warm, golden light over their entwined forms, creating an intimate cocoon where time seemed to stand still. She lay nestled against him, her head resting on his arm, their legs intertwined in a perfect dance of love. His breath was warm against her neck, each exhale a soft caress that sent shivers down her spine. They moved together in a slow, steady rhythm, each shift a new expression of their affection. The room was filled with the soft sounds of their shared breathing, a quiet symphony that spoke of their deep, unbreakable bond. In this quiet moment, they found a sense of peace and fulfillment, their love a gentle, ever-present force that filled their hearts with warmth and contentment.",

    "Spooning_Bedroom": "Wrapped up in the sheets, they spooned slowly, savoring each other's warmth and every lingering moment of connection. The bedroom was a sanctuary of comfort and intimacy, the soft sheets cool against their skin, creating a soothing contrast to the heat radiating from their bodies. She lay nestled against him, her back pressed firmly against his chest, their bodies moving together in a slow, sensual dance. His hand rested on her hip, holding her close, each touch a silent affirmation of his love. The soft glow of moonlight filtered through the curtains, casting a gentle, silvery light over them, adding a touch of magic to the moment. As they moved together in perfect harmony, they whispered sweet words of love and devotion, their voices soft and filled with emotion. They savored each touch, each breath, each beat of their hearts, finding joy in the simple act of being close. In this sacred space, they found a deep, abiding peace, their love a warm, comforting presence that surrounded them like a soft, cozy blanket.",

    "Spooning_Bathroom": "In the warmth of the bathroom, they spooned under the running water, their bodies finding solace in the tender embrace of the shower. The water cascaded over them, creating a soothing, rhythmic sound that filled the room and added a sensory layer to their intimacy. She leaned back against him, feeling the solid warmth of his body against hers, the water flowing over them like a gentle, cleansing rain. His hands moved slowly over her body, tracing gentle patterns on her skin, finding comfort in the softness of her curves. The steam rose around them, creating a private world where nothing existed but their love and the warm, comforting water. They moved together in a slow, deliberate rhythm, their bodies swaying in perfect harmony to the gentle beat of the falling water. As they held each other close, they found a quiet, profound connection, a bond that was strengthened with every touch, every whisper, every shared breath. In this intimate moment, they were completely at peace, their love a gentle, ever-present force that filled their hearts with warmth and contentment.",

    "Spooning_Library": "Among the rows of books, they spooned on the soft carpet, their bodies intertwining in a gentle, passionate embrace of literary romance. The library was a place of quiet contemplation, filled with the soft scent of old books and leather, creating an atmosphere that was both scholarly and sensual. They lay nestled together on the plush carpet, her back pressed firmly against his chest, their bodies fitting together like pieces of a puzzle. His arm draped over her waist, holding her close, each touch a wordless expression of his love. The soft rustle of pages turning was a subtle soundtrack to their quiet, intimate dance, adding a touch of magic to the moment. As they moved together in a slow, steady rhythm, they found themselves lost in a world of their own making, a place where love was the only reality that mattered. In this sacred space of knowledge and wisdom, they found a new kind of learning, one that was both intellectual and deeply, passionately physical. Their love was a story written in touch and breath, a narrative that unfolded with every beat of their hearts.",
};

document.getElementById('positionDice').addEventListener('click', function () {
    rollDice('positionDice', positions);
});

document.getElementById('locationDice').addEventListener('click', function () {
    rollDice('locationDice', locations);
});

document.getElementById('playButton').addEventListener('click', function () {
    narrateStory();
});

document.getElementById('pauseButton').addEventListener('click', function () {
    pauseNarration();
});

document.getElementById('resumeButton').addEventListener('click', function () {
    resumeNarration();
});

document.getElementById('stopButton').addEventListener('click', function () {
    stopNarration();
});

let utterance;

function rollDice(diceId, items) {
    const dice = document.getElementById(diceId);
    dice.classList.add('rolling'); // Add rolling animation class

    setTimeout(() => {
        dice.classList.remove('rolling'); // Remove after animation
        const randomItem = items[Math.floor(Math.random() * items.length)];
        Array.from(dice.children).forEach(face => face.textContent = randomItem); // Update all faces with the new value
        const position = document.querySelector('#positionDice .front').textContent;
        const location = document.querySelector('#locationDice .front').textContent;
        checkForStory(position, location); // Update the checkForStory to use specific faces
    }, 1000); // Match the animation duration
}

function checkForStory(position, location) {
    const key = `${position}_${location}`;
    const storyPage = document.getElementById('storyPage');
    const book = document.getElementById('eroticBook');

    if (stories[key]) {
        storyPage.textContent = stories[key];
        book.style.display = 'block';
        stopNarration(); // Stop any current narration when a new story is loaded
    } else {
        book.style.display = 'none';
    }
}

function narrateStory() {
    const storyText = document.getElementById('storyPage').textContent;
    if (storyText) {
        if (window.speechSynthesis.speaking) {
            stopNarration(); // Stop current narration before starting a new one
        }
        utterance = new SpeechSynthesisUtterance(storyText);
        window.speechSynthesis.speak(utterance);
    }
}

function pauseNarration() {
    if (window.speechSynthesis.speaking && !window.speechSynthesis.paused) {
        window.speechSynthesis.pause();
    }
}

function resumeNarration() {
    if (window.speechSynthesis.paused) {
        window.speechSynthesis.resume();
    }
}

function stopNarration() {
    if (window.speechSynthesis.speaking || window.speechSynthesis.paused) {
        window.speechSynthesis.cancel();
    }
}